name: Auto Close All Open Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day (you can change the cron schedule as needed)
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  close_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Allows the action to close issues

    steps:
      - name: Close all open issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all open issues in the repository
          issues=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open")

          # Check if there are any open issues, and if so, close them
          echo "$issues" | jq -r '.[].number' | while read issue_number; do
            echo "Closing issue #$issue_number"
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
          done
